# 예제 12-7 소비자 서비스를 이스타오로 배포한다

apiVersion: v1
kind: Service
metadata:
  name: ftgo-consumer-service
spec:
  ports:
- name: http
  port: 8080
  targetPort: 8080
  selector:
    app: ftgo-consumer-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ftgo-consumer-service-v2
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: ftgo-consumer-service
          version: v2
      spec:
        containers:
        - image: ftgo-consumer-service:v2
...
