# 예제 12-6 NodePort 서비스의 YAML 파일: 소비자 서비스의 30000번 포트로 트래픽을 라우팅한다

apiVersion: v1
kind: Service
metadata:
  name: ftgo-api-gateway
spec:
type: NodePort
ports:
  - nodePort: 30000
    port: 80
    targetPort: 8080
  selector:
    app: ftgo-api-gateway
---
